# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 19962c77bbfd9c8ead22826f5df3deed8e4725b46c24054f496e50a714c21907694b15137dd94de407ec9423fe26d0c46148bba0df4c058210f71f87a07a811a

test:
  secret_key_base: dca3c4f3a1307eb70619e660c08bd8467be976f6f7596c47275e129382c84bf7048d934389c5929c2275a73df5bc0e375e3dbc21ccb94fb5fd04a8901faf7fcf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
