development: &default
  adapter: postgresql
  database: lesson_9_development
  encoding: unicode
  min_massages: warning
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000